/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData add = const IconData(0xe800, fontFamily: _kFontFam);

      static const IconData babyFood =
      const IconData(0xe801, fontFamily: _kFontFam);
      static const IconData babyStroller =
      const IconData(0xe802, fontFamily: _kFontFam);
      static const IconData babyIcon =
      const IconData(0xe803, fontFamily: _kFontFam);
      static const IconData diaper =
      const IconData(0xe804, fontFamily: _kFontFam);
      static const IconData feedingBottle =
      const IconData(0xe805, fontFamily: _kFontFam);
      static const IconData motherWithBabyInArms =
      const IconData(0xe80b, fontFamily: _kFontFam);
      static const IconData thermometerTool =
      const IconData(0xe813, fontFamily: _kFontFam);
            static const IconData vaccine =
      const IconData(0xe814, fontFamily: _kFontFam);
      static const IconData wrappedBaby =
      const IconData(0xe815, fontFamily: _kFontFam);

  static const IconData people_fill =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData man =
      const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData woman =
      const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData search_lineal =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData bookmark_lineal =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData bookmark_fill =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe80e, fontFamily: _kFontFam);
}
